#!/usr/bin/env bash
# Regenerates the TypeScript ABI module from the Solidity interfaces.
# --json is mandatory: the table form drops struct components entirely.
set -euo pipefail
cd "$(dirname "$0")/.."

{
  echo "// Generated by contracts/abi/generate.sh. Do not edit."
  echo "import type { Abi } from 'viem' // type-only: erased at build, 0 bytes in the WASM bundle"
  echo
  for pair in "ICaplaneRegistry:registryAbi" "ICaplaneInbox:inboxAbi"; do
    contract="${pair%%:*}"
    name="${pair##*:}"
    printf 'export const %s = %s as const satisfies Abi\n\n' \
      "$name" "$(arc-forge inspect "$contract" abi --json)"
  done
} > abi/index.ts
